CREATE TABLE IF NOT EXISTS cliente(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	nome TEXT NOT NULL,
	cpf TEXT(11) NOT NULL,
	email TEXT,
	fone TEXT NOT NULL,
	login TEXT NOT NULL UNIQUE,
	senha TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS servico(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	nome TEXT NOT NULL,
	descricao TEXT NOT NULL,
	preco FLOAT NOT NULL,
	tempo INTEGER NOT NULL,
	tipo TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS atendimento(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	id_cliente INTEGER NOT NULL,
	id_servico INTEGER NOT NULL,
	data TEXT NOT NULL,
	horario TEXT NOT NULL,
	STATUS TEXT NOT NULL,
	FOREIGN KEY (id_cliente) REFERENCES CLIENTE(id),
	FOREIGN KEY (id_servico) REFERENCES SERVICO(id)
);

CREATE TABLE IF NOT EXISTS ADMIN(
	login TEXT PRIMARY KEY,
	senha TEXT NOT NULL,
	nome TEXT NOT NULL
);