from .admin import TelaPrincipalAdmin
from .cliente import TelaPrincipalCliente
from .dirbackup import TelaDiretoriosBackup
from .filtrar_veiculos import TelaFiltrar
from .login import TelaLogin
from .preferencias import TelaPreferencias
from .cadastro import TelaCadastro
from .frameServico import ServicoFrame
from .frameAtendimento import AtendimentoFrame
from .funcs import *
